list: $/bhasha/xinstitute/models/student/columns.yaml
modelClass: Bhasha\Xinstitute\Models\Student
title: Students
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'bhasha/xinstitute/students/update/:id'
